# Generated by Django 4.1.4 on 2022-12-17 19:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.CharField(help_text='Optional- please use urls with jpg, png or jpeg format', max_length=100, validators=[django.core.validators.RegexValidator('([^\\\\s]+(\\\\.(?i)(jpe?g|png|gif|bmp))$)')])),
                ('starting_bid', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(10000000, 2)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('winner_id', models.IntegerField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category')),
                ('owner_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
