# Generated by Django 4.1.4 on 2022-12-18 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(help_text='Optional- please use urls with jpg, png or jpeg format', max_length=100, validators=[django.core.validators.RegexValidator(regex='([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='winner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
