# Generated by Django 4.1.4 on 2022-12-18 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner_Id',
            new_name='owner_id',
        ),
    ]
