# Generated by Django 4.1.4 on 2023-01-10 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_description_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
