# Generated by Django 4.1.4 on 2023-01-17 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_winning_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(regex='([^\\s]+(\\.(?i)(jpe?g|png|gif|bmp))$)')]),
        ),
    ]
